domain_path: /home/ishfisav/vitis_workspace/eth_1G/zynqmp_fsbl/zynqmp_fsbl_bsp
app_src_dir: /home/ishfisav/Desktop/amd2025.2/2025.2/Vitis/data/embeddedsw/lib/sw_apps/zynqmp_fsbl
template: zynqmp_fsbl
lang: c
