domain_path: /home/ishfisav/vitis_workspace/platform/export/platform/sw/doamin1
app_src_dir: /home/ishfisav/Desktop/amd2025.2/2025.2/Vitis/data/embeddedsw/lib/sw_apps/lwip_echo_server
template: lwip_echo_server
lang: c
